spring:
  application:
    name: purchase-transaction
  
  # Database Configuration
  datasource:
    url: jdbc:h2:mem:wex_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  # Hibernate ORM Configuration
  jpa:
    hibernate:
      # Automatically updates the database schema to match JPA entities
      ddl-auto: update
    # Log SQL statements to the console for debugging
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

  # Enable H2 Console
  h2:
    console:
      enabled: true
      path: /h2-console

treasury:
  api:
    url: https://api.fiscaldata.treasury.gov/services/api/fiscal_service/v1/accounting/od/rates_of_exchange
